[package]
name = "uwufier-service"
version = "0.1.0"
authors = ["vhashimotoo <hashimoto.stream@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
uwuify = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
