apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-board-bot
  labels:
    app: the-board-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-board-bot
  template:
    metadata:
      labels:
        app: the-board-bot
    spec:
      containers:
        - name: the-board-bot
          image: ghcr.io/siberianmh/the-board-bot:latest
          imagePullPolicy: Always
          resources: {}
          envFrom:
            - secretRef:
                name: base-secret
            - secretRef:
                name: the-board-secret
