name: Compile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  #############
  # Compiling #
  #############
  compile-bot:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Compile bot
        run: |
          bazel build //packages/bot

  compile-server:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Compile server
        run: bazel build //packages/server
