name: The Board Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  #############
  # Compiling #
  #############
  compile-the-board:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile The Board
        run: |
          bazel build //packages/the-board
